COMMON: &common
  TABLEDAP: http://data-test.ooi.rutgers.edu/erddap/tabledap/
  ERDDAP_URL: http://data-test.ooi.rutgers.edu/erddap
  SERVICES_URL: http://localhost:4000
  DEBUG: False
  CACHE_TYPE: simple
  UI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  GOOGLE_ANALYTICS: 'UA-50606390-3'
  REDMINE_URL: 'https://localhost'
  SUBSCRIPTION_SERVER: 'http://localhost:12585'
  SAN_DATA_SERVER: 'http://opendap-devel.ooi.rutgers.edu:8080/opendap/hyrax/'
  TROUBLE_TICKETS: 'https://uframe-cm.ooi.rutgers.edu/login'
  UI_APP_IP: 'localhost'
  UI_APP_PORT: 5000
  SERVER_DNS: 'http://10.0.0.14:5000'
  OOI_UI_GITHUB: '34efet54etefg'
  OOI_UI_SERVICES_GITHUB: '34ewrfe5eetrg'
  SMTP_SENDER : 'noreply@oceanobservatories.org'
  SMTP_SERVER: 'localhost'
  SMTP_USERNAME: 'username'
  SMTP_PASSWORD: 'password'
  SMTP_PORT: '25'
  SMTP_DO_TLS: False
  SMTP_AUTH: False
  SECURITY_PASSWORD_HASH : 'pbkdf2_sha512'
  SECURITY_PASSWORD_SALT : 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True


