COMMON: &common
  TABLEDAP: http://data-test.ooi.rutgers.edu/erddap/tabledap/
  ERDDAP_URL: http://data-test.ooi.rutgers.edu/erddap
  SERVICES_URL: http://localhost:4000
  DEBUG: False
  CACHE_TYPE: simple
  UI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  GOOGLE_ANALYTICS_URL: 'http://www.google-analytics.com/collect?v=1&tid=UA-50606390-3&cid=5555&t=pageview'
  REDMINE_URL: 'https://localhost'
  SUBSCRIPTION_SERVER: 'http://localhost:12585'
  SAN_DATA_SERVER: 'http://opendap-devel.ooi.rutgers.edu:8080/opendap/hyrax/'
  TROUBLE_TICKETS: 'https://uframe-cm.ooi.rutgers.edu/login'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True


